// <auto-generated />
namespace SuperrHero.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedpropertyoftypeDbSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedpropertyoftypeDbSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011659174_Added property of type DbSet."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
